# Generated by Django 2.1.1 on 2018-10-24 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181015_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='驗證碼')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('send_type', models.CharField(choices=[('register', '註冊'), ('forget', '找回密碼')], max_length=10, verbose_name='驗證碼類型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='發送時間')),
            ],
            options={
                'verbose_name': 'Email驗證碼',
                'verbose_name_plural': 'Email驗證碼',
            },
        ),
    ]
