# Generated by Django 2.1.1 on 2018-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BigIntegerField(default=0, max_length=2),
        ),
    ]
