# Generated by Django 2.1.1 on 2018-11-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181027_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=20)),
                ('std_id', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('is_PE', models.IntegerField(default=0, max_length=1)),
                ('is_foreign', models.IntegerField(default=0, max_length=1)),
                ('id_number', models.CharField(max_length=10)),
                ('cellphone', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=5)),
                ('pic_1', models.ImageField(upload_to='pic')),
                ('pic_2', models.ImageField(upload_to='pic')),
                ('pic_3', models.ImageField(upload_to='pic')),
                ('pic_4', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=10, unique=True)),
                ('not_active', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=20)),
                ('std_id', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('is_PE', models.IntegerField(default=0, max_length=1)),
                ('is_foreign', models.IntegerField(default=0, max_length=1)),
                ('id_number', models.CharField(max_length=10)),
                ('cellphone', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=5)),
                ('pic_1', models.ImageField(upload_to='pic')),
                ('pic_2', models.ImageField(upload_to='pic')),
                ('pic_3', models.ImageField(upload_to='pic')),
                ('pic_4', models.ImageField(upload_to='pic')),
                ('TeamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Team')),
            ],
        ),
        migrations.AddField(
            model_name='realteammember',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Team'),
        ),
    ]
