# Generated by Django 2.1.1 on 2018-11-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181104_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realteammember',
            name='is_PE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realteammember',
            name='is_foreign',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_PE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_foreign',
            field=models.IntegerField(default=0),
        ),
    ]
