# Generated by Django 2.1.1 on 2018-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20181104_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='is_pass',
            field=models.IntegerField(default=0),
        ),
    ]
