# Generated by Django 2.1.1 on 2018-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='memberNum',
            field=models.IntegerField(default=0),
        ),
    ]
