# Generated by Django 2.1.1 on 2018-11-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_team_membernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realteammember',
            name='pic_1',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='realteammember',
            name='pic_2',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='realteammember',
            name='pic_3',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='realteammember',
            name='pic_4',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='pic_1',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='pic_2',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='pic_3',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='pic_4',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
