# Generated by Django 2.1.1 on 2018-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181107_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realteammember',
            name='member',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member',
            field=models.CharField(max_length=40),
        ),
    ]
