# Generated by Django 2.1.1 on 2018-11-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20181111_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='realteammember',
            name='reg_time',
            field=models.DateTimeField(auto_now=True, verbose_name='報名時間'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='reg_time',
            field=models.DateTimeField(auto_now=True, verbose_name='報名時間'),
        ),
    ]
