# Generated by Django 2.1.1 on 2018-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20181111_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='realteammember',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='是否提交隊員資料'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='是否提交隊員資料'),
        ),
    ]
