# Generated by Django 2.1.1 on 2018-11-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20181111_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='upload_paid',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='是否上傳付費照'),
        ),
    ]
