# Generated by Django 2.1.1 on 2018-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20181121_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active_time',
            field=models.DateTimeField(auto_now=True, verbose_name='報名時間'),
        ),
    ]
