# Generated by Django 2.1.1 on 2018-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_team_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active_time',
            field=models.DateTimeField(verbose_name='報名時間'),
        ),
    ]
